apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
  labels: 
    app: goserver
spec: 
  selector: 
    matchLabels: 
      app: goserver
  replicas: 1
  template: 
    metadata:
      labels:
        app: "goserver" 
    spec: 
      containers:
        - name: goserver
          image: "lucasasilvaa/hello-go:v4"
          env: 
            - name: NAME
              value: "Lucas"
            - name: AGE
              value: "25"