apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
  labels: 
    app: goserver
spec: 
  selector: 
    matchLabels: 
      app: goserver
  replicas: 1
  template: 
    metadata:
      labels:
        app: "goserver" 
    spec: 
      containers:
        - name: goserver
          image: "lucasasilvaa/hello-go:v5"
          envFrom: 
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - mountPath: "/go/family"
              name: config
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: family.txt