apiVersion: v1
kind: Service
metadata: 
  name: goserver-service
spec: 
  selector:
    app: goserver
  type: ClusterIP
  ports: 
  - name: goserver-service
    port: 3000
    targetPort: 8080
    protocol: TCP
    # nodePort: 30001 #30000 32767  